/**
 * Insight Domain Types
 *
 * Normalized domain contracts for project-level insight persistence and
 * insight-generation run tracking.
 *
 * Design principles:
 * - Insights are **project-scoped** — each insight belongs to exactly one project
 * - **Deduplication** via canonical fingerprint: same fingerprint = same logical insight
 * - **Stable identity**: upserts preserve the original `id` and `createdAt`
 * - **Deterministic ordering**: list operations use multi-column tie-breakers
 *   (see ordering contract below)
 *
 * ## Ordering Contract
 *
 * All list operations return results in **ascending** order by default.
 * When multiple rows share the same primary sort key (e.g., `createdAt`),
 * the tie is broken deterministically by:
 *
 *   1. `id` ascending (lexicographic, case-sensitive)
 *
 * This two-level ordering is enforced in both SQL ORDER BY clauses and
 * in-memory sorts to guarantee stable iteration across repeated reads.
 * Timestamp-only ordering is intentionally avoided because SQLite timestamps
 * have millisecond resolution, making ties possible in batch operations.
 *
 * ## Naming Convention
 *
 * Table names use `project_insights` / `project_insight_runs` (snake_case)
 * to match the established SQLite convention in this codebase.
 * Type names use PascalCase (e.g., `Insight`, `InsightRun`).
 */

// ── Insight Category ─────────────────────────────────────────────────

/** High-level category for classifying an insight. */
export type InsightCategory =
  | "quality"        // Code quality, patterns, debt
  | "performance"    // Performance, efficiency, bottlenecks
  | "architecture"   // Structural decisions, coupling, design
  | "security"       // Security vulnerabilities, risks
  | "reliability"    // Error handling, stability, resilience
  | "ux"             // User experience, accessibility, ergonomics
  | "testability"    // Testing gaps, coverage, test design
  | "documentation"  // Docs, comments, clarity
  | "dependency"     // Third-party deps, versions, updates
  | "workflow"       // Process, tooling, developer experience
  | "other"          // Uncategorized / general
  | "features"      // Product feature opportunities
  | "competitive_analysis" // Competitive landscape analysis
  | "research"      // Market and user research insights
  | "trends";       // Industry and technology trends

// ── Insight Lifecycle ─────────────────────────────────────────────────

/**
 * Lifecycle state of an insight.
 *
 * State transitions:
 *   generated → confirmed → stale
 *                  ↓
 *               dismissed
 *
 * A "stale" insight has been superseded or is no longer relevant.
 * A "dismissed" insight was manually rejected by a reviewer.
 */
export type InsightStatus = "generated" | "confirmed" | "stale" | "dismissed";

// ── Provenance Metadata ───────────────────────────────────────────────

/**
 * Provenance metadata capturing where/how an insight was derived.
 * Stored as a JSON column in the database.
 */
export interface InsightProvenance {
  /**
   * What triggered this insight to be generated.
   * Examples: "schedule", "manual", "task_completion", "merge_event"
   */
  trigger: string;

  /** Human-readable description of the generation context. */
  description?: string;

  /**
   * Identifiers of related entities that were in scope when the insight
   * was generated. For example, task IDs that were analyzed.
   */
  relatedEntityIds?: string[];

  /**
   * Token usage estimate for the generation call.
   * Stored as an approximate snapshot, not for billing purposes.
   */
  tokenEstimate?: {
    input?: number;
    output?: number;
  };

  /**
   * Arbitrary metadata specific to the generation method.
   * Examples: model ID, temperature, processing duration.
   */
  metadata?: Record<string, unknown>;
}

// ── Core Insight Entity ───────────────────────────────────────────────

/**
 * A persisted project insight.
 *
 * An insight represents a derived observation or recommendation about
 * the project, generated by an AI analysis pipeline and stored for
 * later review, action, or archival.
 *
 * Identity is determined by `id`; dedup logic uses `fingerprint`.
 */
export interface Insight {
  /**
   * Unique identifier (e.g., "INS-xxx").
   * Assigned by the store on creation; stable across upserts.
   */
  id: string;

  /**
   * Project this insight belongs to.
   * Corresponds to the project directory / .fusion/ path.
   */
  projectId: string;

  /** Short title summarizing the insight (1–120 chars recommended). */
  title: string;

  /**
   * Full body of the insight. May contain markdown formatting.
   * Nullable to support partial insights (title-only during generation).
   */
  content: string | null;

  /**
   * Classification category.
   */
  category: InsightCategory;

  /**
   * Current lifecycle state.
   */
  status: InsightStatus;

  /**
   * Canonical fingerprint for deduplication.
   *
   * Two insights with the same fingerprint and projectId are considered
   * the same logical insight. When an upsert finds a matching fingerprint,
   * the existing row is updated and its `id` / `createdAt` are preserved.
   *
   * Construction: a deterministic hash of (normalized title + category).
   * Consumers should use `computeInsightFingerprint()` from insight-store.ts.
   */
  fingerprint: string;

  /**
   * Provenance metadata capturing the generation context.
   */
  provenance: InsightProvenance;

  /**
   * ID of the most recent generation run that produced or updated this insight.
   * References `project_insight_runs.id`.
   */
  lastRunId: string | null;

  /**
   * When the insight was first generated.
   * Set on creation and preserved on upsert.
   */
  createdAt: string;

  /**
   * When the insight was last modified (any field change).
   */
  updatedAt: string;
}

// ── Insight Creation Input ───────────────────────────────────────────

/**
 * Input for creating a new insight.
 * `fingerprint` is required for upsertable insights.
 */
export interface InsightCreateInput {
  title: string;
  content?: string | null;
  category: InsightCategory;
  provenance: InsightProvenance;
  fingerprint?: string;
  status?: InsightStatus;
}

// ── Insight Update Input ─────────────────────────────────────────────

/**
 * Input for updating an existing insight.
 * All fields are optional — only provided fields are updated.
 */
export interface InsightUpdateInput {
  title?: string;
  content?: string | null;
  category?: InsightCategory;
  status?: InsightStatus;
  provenance?: InsightProvenance;
}

// ── Insight Upsert Input ─────────────────────────────────────────────

/**
 * Input for upserting an insight by fingerprint.
 *
 * If an existing insight with the same (projectId, fingerprint) exists,
 * the mutable fields are updated and the original `id` / `createdAt` are
 * preserved (no duplicate row is created).
 *
 * If no match exists, a new insight is created with a fresh `id`.
 */
export interface InsightUpsertInput extends InsightCreateInput {
  /**
   * Required for upsert — must be provided to enable dedupe matching.
   */
  fingerprint: string;
}

// ── Insight List Options ─────────────────────────────────────────────

/**
 * Filtering and pagination options for insight listing.
 */
export interface InsightListOptions {
  /** Restrict to a specific project. */
  projectId?: string;

  /** Restrict to a specific category. */
  category?: InsightCategory;

  /** Restrict to a specific status. */
  status?: InsightStatus;

  /** Restrict to insights linked to a specific run. */
  runId?: string;

  /** Maximum number of rows to return. Default: no limit. */
  limit?: number;

  /** Number of rows to skip. Default: 0. */
  offset?: number;
}

// ── Insight Generation Run Entity ────────────────────────────────────

/**
 * Status of a single insight-generation run.
 *
 * Runs are **immutable** once terminal (completed, failed, cancelled).
 * Only `pending` and `running` runs can transition state.
 */
export type InsightRunStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

/**
 * What triggered a generation run.
 */
export type InsightRunTrigger = "schedule" | "manual" | "task_completion" | "merge_event" | "api";

/**
 * A single execution of the insight-generation pipeline.
 *
 * Runs track the full lifecycle of an analysis pass — from scheduling
 * through input processing to output persistence.
 */
export type InsightRunFailureClass = "cancelled" | "timed_out" | "retryable_transient" | "non_retryable";

export interface InsightRunLifecycle {
  terminalReason?: "completed" | "cancelled" | "failed" | "timed_out";
  terminalCause?: string;
  failureClass?: InsightRunFailureClass;
  retryable?: boolean;
  cancellationRequestedAt?: string;
  timeoutAt?: string;
  retryOfRunId?: string;
  rootRunId?: string;
  attempt?: number;
  maxAttempts?: number;
}

export type InsightRunEventType =
  | "status_changed"
  | "retry_scheduled"
  | "cancel_requested"
  | "timeout"
  | "info"
  | "warning"
  | "error";

export interface InsightRunEvent {
  id: string;
  runId: string;
  seq: number;
  type: InsightRunEventType;
  message: string;
  status?: InsightRunStatus;
  classification?: InsightRunFailureClass;
  metadata?: Record<string, unknown>;
  createdAt: string;
}

export interface InsightRun {
  /**
   * Unique identifier for this run (e.g., "INSR-xxx").
   * Assigned by the store on creation.
   */
  id: string;

  /**
   * Project this run belongs to.
   */
  projectId: string;

  /**
   * What initiated this run.
   */
  trigger: InsightRunTrigger;

  /**
   * Current execution status.
   */
  status: InsightRunStatus;

  /**
   * Human-readable summary of the run outcome.
   * Set by the pipeline on completion or failure.
   */
  summary: string | null;

  /**
   * Error message if the run failed.
   */
  error: string | null;

  /**
   * Number of insights that were created by this run.
   */
  insightsCreated: number;

  /**
   * Number of existing insights that were updated (fingerprint-matched) by this run.
   */
  insightsUpdated: number;

  /**
   * Input metadata for the run — what was analyzed.
   * Stored as a JSON snapshot for audit/replay.
   */
  inputMetadata: InsightRunInputMetadata;

  /**
   * Output metadata for the run — what was produced.
   * Stored as a JSON snapshot.
   */
  outputMetadata: InsightRunOutputMetadata;

  /**
   * When the run was queued / created.
   */
  createdAt: string;

  /**
   * When the run started processing.
   */
  startedAt: string | null;

  /**
   * When the run reached a terminal state.
   */
  completedAt: string | null;

  /**
   * When cancellation was applied.
   */
  cancelledAt: string | null;

  lifecycle: InsightRunLifecycle;
}

// ── Run Input / Output Metadata ──────────────────────────────────────

/**
 * Input metadata snapshot for a run.
 */
export interface InsightRunInputMetadata {
  /**
   * IDs of tasks that were in scope for this analysis.
   * Empty array if no task-specific scope.
   */
  taskIds?: string[];

  /**
   * Branch or ref that was analyzed (if applicable).
   */
  branch?: string;

  /**
   * Commit SHA at which analysis was performed.
   */
  commitSha?: string;

  /**
   * Any additional context passed to the generation prompt.
   */
  context?: string;

  /**
   * Arbitrary input metadata (model used, prompt tokens, etc.).
   */
  metadata?: Record<string, unknown>;
}

/**
 * Output metadata snapshot for a run.
 */
export interface InsightRunOutputMetadata {
  /**
   * IDs of insights created by this run.
   */
  insightIds?: string[];

  /**
   * IDs of existing insights updated (fingerprint-matched) by this run.
   */
  updatedInsightIds?: string[];

  /**
   * IDs of insights that were marked stale or dismissed by this run.
   */
  supersededInsightIds?: string[];

  /**
   * Number of generation prompt tokens used.
   */
  promptTokens?: number;

  /**
   * Number of completion tokens generated.
   */
  completionTokens?: number;

  /**
   * Arbitrary output metadata.
   */
  metadata?: Record<string, unknown>;
}

// ── Run Creation Input ───────────────────────────────────────────────

/**
 * Input for creating a new insight run.
 */
export interface InsightRunCreateInput {
  trigger: InsightRunTrigger;
  inputMetadata?: InsightRunInputMetadata;
  lifecycle?: InsightRunLifecycle;
}

// ── Run Update Input ─────────────────────────────────────────────────

/**
 * Input for updating a run record.
 * Used by the pipeline to report progress and final outcomes.
 */
export interface InsightRunUpdateInput {
  status?: InsightRunStatus;
  summary?: string | null;
  error?: string | null;
  insightsCreated?: number;
  insightsUpdated?: number;
  outputMetadata?: InsightRunOutputMetadata;
  lifecycle?: InsightRunLifecycle;
  startedAt?: string | null;
  completedAt?: string | null;
  cancelledAt?: string | null;
}

// ── Run List Options ─────────────────────────────────────────────────

/**
 * Filtering and pagination options for run listing.
 */
export interface InsightRunListOptions {
  /** Restrict to a specific project. */
  projectId?: string;

  /** Restrict to runs with a specific status. */
  status?: InsightRunStatus;

  /** Restrict to runs triggered by a specific trigger type. */
  trigger?: InsightRunTrigger;

  /** Maximum number of rows to return. Default: no limit. */
  limit?: number;

  /** Number of rows to skip. Default: 0. */
  offset?: number;
}

// ── Store Event Types ────────────────────────────────────────────────

export interface InsightStoreEvents {
  /** Emitted when an insight is created */
  "insight:created": [Insight];
  /** Emitted when an insight is updated */
  "insight:updated": [Insight];
  /** Emitted when an insight is deleted */
  "insight:deleted": [string];
  /** Emitted when a run is created */
  "run:created": [InsightRun];
  /** Emitted when a run is updated */
  "run:updated": [InsightRun];
  /** Emitted when a run reaches a terminal state */
  "run:completed": [InsightRun];
  /** Emitted when a durable run event is appended */
  "run:event": [{ runId: string; event: InsightRunEvent }];
}
